name: Build GitBook PDF and EPUB

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js v12
        uses: actions/setup-node@v4
        with:
          node-version: '12.x'

      - name: Install gitbook-cli
        run: npm install -g gitbook-cli

      # We now install all required system dependencies in one step
      - name: Install system dependencies for Calibre
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 libopengl0 libxcb-cursor0

      - name: Install Calibre for PDF generation
        run: |
          sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

      - name: Install book plugins
        run: gitbook install

      - name: Build PDF and EPUB
        run: |
          gitbook pdf . book.pdf
          gitbook epub . book.epub

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-pdf
          path: book.pdf

      - name: Upload EPUB artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-epub
          path: book.epub
